name: Simple Workflow

on:
  push:
    branches:
      - main  # Or your default branch

jobs:
  simple-job:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run a simple command
        run: echo "GitHub Actions is running!"
