name: Update jackbox.txt

on:
  push:
    paths:
      - 'jackbox.txt'  # Monitor changes to the data file

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up the directory for deployment
      - name: Create deployment folder
        run: |
          mkdir deploy_folder
          copy jackbox.txt deploy_folder\jackbox.txt

      # Step 3: Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: mattu82
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: './deploy_folder'  # Specify the directory containing the file
